version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - sudo apt-get update -y
  build:
    commands:
      - echo Build started on `date`
      - echo Build phase complete

artifacts:
  files:
    - '**/*'
